---
title: "assignment4"
output: html_document
date: "2025-09-20"
---

```{r setup, include=FALSE}
library(readxl)

df_hosp <- read_excel("C:/Users/Willi/OneDrive/Desktop/Module # 4 assessment_data.xlsx")

str(df_hosp)

# Inspect and handle NA:
summary(df_hosp)
df_hosp <- na.omit(df_hosp)
```

## R Markdown

Boxplots

```{r cars}
boxplot(
  BloodPressure ~ FirstAssess,
  data = df_hosp,
  names = c("Good","Bad"),
  ylab = "Blood Pressure",
  main = "BP by First MD Assessment",
  col = c("lightblue", "tomato")
)

boxplot(
  BloodPressure ~ SecondAssess,
  data = df_hosp,
  names = c("Low","High"),
  ylab = "Blood Pressure",
  main = "BP by Second MD Assessment",
  col = c("lightblue", "tomato")
)

boxplot(
  BloodPressure ~ FinalDecision,
  data = df_hosp,
  names = c("Low","High"),
  ylab = "Blood Pressure",
  main = "BP by Final Decision",
  col = c("lightblue", "tomato")
)


```

## Including Plots

Histograms

```{r pressure, echo=FALSE}
h1 <- hist(
  df_hosp$Frequency,
  breaks = seq(0, 1, by = 0.1),
  xlab = "Visit Frequency",
  main = "Histogram of Visit Frequency",
  col=rgb(0,0,1,1/4))

h2 <- hist(
  df_hosp$BloodPressure,
  breaks = 8,
  xlab = "Blood Pressure",
  main = "Histogram of Blood Pressure",
  col=rgb(1,0,0,1/4))



```

Scatterplot, however there is aboslutely no pattern to seen here

```{r}
library(ggplot2)
 

ggplot(df_hosp, aes(x=Frequency, y=BloodPressure)) + 
    geom_point()
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
